#!/usr/bin/env bash
# Script to configure and install a web-server
# and attach an header

sudo apt-get update -y
sudo apt-get install nginx -y

sudo sed -i "/http {/a \ \t add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart
