#!/usr/bin/env bash
# install and configure HAproxy load balancer
# lb-01 server

sudo apt-get -y install software-properties-common

sudo add-apt-repository ppa:vbernat/haproxy-2.7

sudo apt-get -y update

sudo apt-get install haproxy=2.7.\*

echo -e "frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web_backend\n\nbackend web_backend\n\tbalance roundrobin\n\tserver 35019-web-01 52.204.211.141 check\n\tserver 35019-web-02 100.25.48.240 check" >> etc/haproxy/haproxy.cfg

sudo service haproxy restart
